// SPDX-License-Identifier: Apache-2.0
#ifndef APTA_WINDOWS_EXPORTS_H
#define APTA_WINDOWS_EXPORTS_H

/*
 * MSVC does not infer DLL exports for public wrappers whose implementation
 * is composed through private source-level aliases. Keep the linker export
 * directives identical to abi/public-symbols-1.0.txt; the shared-library
 * ABI test rejects both missing and unexpected apta_* exports.
 */
#if defined(_MSC_VER) && defined(APTA_SHARED) && \
    defined(APTA_BUILDING_LIBRARY)
#  pragma comment(linker, "/export:apta_allocator_init")
#  pragma comment(linker, "/export:apta_clock_init")
#  pragma comment(linker, "/export:apta_context_config_init")
#  pragma comment(linker, "/export:apta_context_create")
#  pragma comment(linker, "/export:apta_context_destroy")
#  pragma comment(linker, "/export:apta_context_get_capabilities")
#  pragma comment(linker, "/export:apta_diagnostic_view_init")
#  pragma comment(linker, "/export:apta_focus_init")
#  pragma comment(linker, "/export:apta_frame_range_init")
#  pragma comment(linker, "/export:apta_grid_revision_view_init")
#  pragma comment(linker, "/export:apta_grid_view_init")
#  pragma comment(linker, "/export:apta_logger_init")
#  pragma comment(linker, "/export:apta_memory_requirements_init")
#  pragma comment(linker, "/export:apta_metadata_init")
#  pragma comment(linker, "/export:apta_metadata_view_init")
#  pragma comment(linker, "/export:apta_parse_options_init")
#  pragma comment(linker, "/export:apta_pcm_block_init")
#  pragma comment(linker, "/export:apta_pcm_request_init")
#  pragma comment(linker, "/export:apta_pcm_source_init")
#  pragma comment(linker, "/export:apta_progress_init")
#  pragma comment(linker, "/export:apta_query_memory_requirements")
#  pragma comment(linker, "/export:apta_query_workspace_requirements")
#  pragma comment(linker, "/export:apta_region_request_init")
#  pragma comment(linker, "/export:apta_request_progress_init")
#  pragma comment(linker, "/export:apta_result_get_available_features")
#  pragma comment(linker, "/export:apta_result_get_beatgrid")
#  pragma comment(linker, "/export:apta_result_get_diagnostic")
#  pragma comment(linker, "/export:apta_result_get_diagnostic_count")
#  pragma comment(linker, "/export:apta_result_get_feature_state")
#  pragma comment(linker, "/export:apta_result_get_generation")
#  pragma comment(linker, "/export:apta_result_get_grid_revision")
#  pragma comment(linker, "/export:apta_result_get_info")
#  pragma comment(linker, "/export:apta_result_get_metadata")
#  pragma comment(linker, "/export:apta_result_get_source_info")
#  pragma comment(linker, "/export:apta_result_get_tempo")
#  pragma comment(linker, "/export:apta_result_get_waveform_overview")
#  pragma comment(linker, "/export:apta_result_get_waveform_tile")
#  pragma comment(linker, "/export:apta_result_info_init")
#  pragma comment(linker, "/export:apta_result_parse")
#  pragma comment(linker, "/export:apta_result_query_serialized_size")
#  pragma comment(linker, "/export:apta_result_release")
#  pragma comment(linker, "/export:apta_result_serialize")
#  pragma comment(linker, "/export:apta_serialize_options_init")
#  pragma comment(linker, "/export:apta_session_acquire_result")
#  pragma comment(linker, "/export:apta_session_apply_grid_revision")
#  pragma comment(linker, "/export:apta_session_cancel_region_request")
#  pragma comment(linker, "/export:apta_session_config_init")
#  pragma comment(linker, "/export:apta_session_create")
#  pragma comment(linker, "/export:apta_session_destroy")
#  pragma comment(linker, "/export:apta_session_get_request_progress")
#  pragma comment(linker, "/export:apta_session_get_state")
#  pragma comment(linker, "/export:apta_session_is_cancel_requested")
#  pragma comment(linker, "/export:apta_session_lock_grid_range")
#  pragma comment(linker, "/export:apta_session_next_pcm_request")
#  pragma comment(linker, "/export:apta_session_process")
#  pragma comment(linker, "/export:apta_session_push_pcm")
#  pragma comment(linker, "/export:apta_session_request_cancel")
#  pragma comment(linker, "/export:apta_session_request_region")
#  pragma comment(linker, "/export:apta_session_seed_from_result")
#  pragma comment(linker, "/export:apta_session_set_focus")
#  pragma comment(linker, "/export:apta_session_set_metadata")
#  pragma comment(linker, "/export:apta_session_set_source")
#  pragma comment(linker, "/export:apta_session_signal_end_of_input")
#  pragma comment(linker, "/export:apta_source_info_init")
#  pragma comment(linker, "/export:apta_tempo_view_init")
#  pragma comment(linker, "/export:apta_waveform_overview_view_init")
#  pragma comment(linker, "/export:apta_waveform_tile_view_init")
#  pragma comment(linker, "/export:apta_work_budget_init")
#endif

#endif /* APTA_WINDOWS_EXPORTS_H */
