// SPDX-License-Identifier: Apache-2.0
#include <stddef.h>
#include <stdio.h>
#include <apta/apta.h>

#define PRINT_TYPE(type_name) \
    printf("type\t%s\t%zu\t%zu\n", #type_name, sizeof(type_name), _Alignof(type_name))
#define PRINT_FIELD(type_name, field_name) \
    printf("field\t%s\t%s\t%zu\n", #type_name, #field_name, offsetof(type_name, field_name))

int main(void)
{
    PRINT_TYPE(apta_allocator_t);
    PRINT_FIELD(apta_allocator_t, struct_size);
    PRINT_FIELD(apta_allocator_t, api_version);
    PRINT_FIELD(apta_allocator_t, user_data);
    PRINT_FIELD(apta_allocator_t, allocate);
    PRINT_FIELD(apta_allocator_t, deallocate);
    PRINT_FIELD(apta_allocator_t, reallocate);
    PRINT_TYPE(apta_logger_t);
    PRINT_FIELD(apta_logger_t, struct_size);
    PRINT_FIELD(apta_logger_t, api_version);
    PRINT_FIELD(apta_logger_t, user_data);
    PRINT_FIELD(apta_logger_t, write);
    PRINT_TYPE(apta_clock_t);
    PRINT_FIELD(apta_clock_t, struct_size);
    PRINT_FIELD(apta_clock_t, api_version);
    PRINT_FIELD(apta_clock_t, user_data);
    PRINT_FIELD(apta_clock_t, monotonic_time_ns);
    PRINT_TYPE(apta_context_config_t);
    PRINT_FIELD(apta_context_config_t, struct_size);
    PRINT_FIELD(apta_context_config_t, api_version);
    PRINT_FIELD(apta_context_config_t, allocator);
    PRINT_FIELD(apta_context_config_t, logger);
    PRINT_FIELD(apta_context_config_t, clock);
    PRINT_FIELD(apta_context_config_t, requested_capabilities);
    PRINT_FIELD(apta_context_config_t, memory_limit_bytes);
    PRINT_FIELD(apta_context_config_t, flags);
    PRINT_FIELD(apta_context_config_t, reserved32);
    PRINT_FIELD(apta_context_config_t, reserved64);
    PRINT_TYPE(apta_session_config_t);
    PRINT_FIELD(apta_session_config_t, struct_size);
    PRINT_FIELD(apta_session_config_t, api_version);
    PRINT_FIELD(apta_session_config_t, input_mode);
    PRINT_FIELD(apta_session_config_t, source_sample_rate);
    PRINT_FIELD(apta_session_config_t, channel_count);
    PRINT_FIELD(apta_session_config_t, reserved16);
    PRINT_FIELD(apta_session_config_t, sample_format);
    PRINT_FIELD(apta_session_config_t, channel_layout);
    PRINT_FIELD(apta_session_config_t, total_frames);
    PRINT_FIELD(apta_session_config_t, requested_features);
    PRINT_FIELD(apta_session_config_t, memory_budget_bytes);
    PRINT_FIELD(apta_session_config_t, static_workspace);
    PRINT_FIELD(apta_session_config_t, static_workspace_size);
    PRINT_FIELD(apta_session_config_t, flags);
    PRINT_FIELD(apta_session_config_t, overview_frames_per_column);
    PRINT_FIELD(apta_session_config_t, source_fingerprint_kind);
    PRINT_FIELD(apta_session_config_t, reserved32);
    PRINT_FIELD(apta_session_config_t, source_fingerprint);
    PRINT_TYPE(apta_memory_requirements_t);
    PRINT_FIELD(apta_memory_requirements_t, struct_size);
    PRINT_FIELD(apta_memory_requirements_t, api_version);
    PRINT_FIELD(apta_memory_requirements_t, minimum_bytes);
    PRINT_FIELD(apta_memory_requirements_t, recommended_bytes);
    PRINT_FIELD(apta_memory_requirements_t, required_alignment);
    PRINT_FIELD(apta_memory_requirements_t, flags);
    PRINT_FIELD(apta_memory_requirements_t, reserved32);
    PRINT_TYPE(apta_utf8_view_t);
    PRINT_FIELD(apta_utf8_view_t, data);
    PRINT_FIELD(apta_utf8_view_t, size);
    PRINT_TYPE(apta_bytes_view_t);
    PRINT_FIELD(apta_bytes_view_t, data);
    PRINT_FIELD(apta_bytes_view_t, size);
    PRINT_TYPE(apta_metadata_t);
    PRINT_FIELD(apta_metadata_t, struct_size);
    PRINT_FIELD(apta_metadata_t, api_version);
    PRINT_FIELD(apta_metadata_t, producer_name);
    PRINT_FIELD(apta_metadata_t, producer_version_string);
    PRINT_FIELD(apta_metadata_t, backend_name);
    PRINT_FIELD(apta_metadata_t, backend_version);
    PRINT_FIELD(apta_metadata_t, creation_unix_time);
    PRINT_FIELD(apta_metadata_t, application_source_id);
    PRINT_FIELD(apta_metadata_t, comments);
    PRINT_FIELD(apta_metadata_t, application_source_id_kind);
    PRINT_FIELD(apta_metadata_t, flags);
    PRINT_FIELD(apta_metadata_t, reserved32);
    PRINT_FIELD(apta_metadata_t, reserved64);
    PRINT_TYPE(apta_metadata_view_t);
    PRINT_FIELD(apta_metadata_view_t, struct_size);
    PRINT_FIELD(apta_metadata_view_t, api_version);
    PRINT_FIELD(apta_metadata_view_t, producer_name);
    PRINT_FIELD(apta_metadata_view_t, producer_version_string);
    PRINT_FIELD(apta_metadata_view_t, backend_name);
    PRINT_FIELD(apta_metadata_view_t, backend_version);
    PRINT_FIELD(apta_metadata_view_t, creation_unix_time);
    PRINT_FIELD(apta_metadata_view_t, application_source_id);
    PRINT_FIELD(apta_metadata_view_t, comments);
    PRINT_FIELD(apta_metadata_view_t, application_source_id_kind);
    PRINT_FIELD(apta_metadata_view_t, flags);
    PRINT_FIELD(apta_metadata_view_t, reserved32);
    PRINT_FIELD(apta_metadata_view_t, reserved64);
    PRINT_TYPE(apta_waveform_column_t);
    PRINT_FIELD(apta_waveform_column_t, minimum);
    PRINT_FIELD(apta_waveform_column_t, maximum);
    PRINT_FIELD(apta_waveform_column_t, rms);
    PRINT_FIELD(apta_waveform_column_t, low);
    PRINT_FIELD(apta_waveform_column_t, mid);
    PRINT_FIELD(apta_waveform_column_t, high);
    PRINT_FIELD(apta_waveform_column_t, flags);
    PRINT_TYPE(apta_waveform_level_info_t);
    PRINT_FIELD(apta_waveform_level_info_t, struct_size);
    PRINT_FIELD(apta_waveform_level_info_t, api_version);
    PRINT_FIELD(apta_waveform_level_info_t, level_id);
    PRINT_FIELD(apta_waveform_level_info_t, frames_per_column);
    PRINT_FIELD(apta_waveform_level_info_t, origin_frame);
    PRINT_FIELD(apta_waveform_level_info_t, flags);
    PRINT_FIELD(apta_waveform_level_info_t, reserved32);
    PRINT_TYPE(apta_waveform_span_t);
    PRINT_FIELD(apta_waveform_span_t, source_range);
    PRINT_FIELD(apta_waveform_span_t, first_column_index);
    PRINT_FIELD(apta_waveform_span_t, column_count);
    PRINT_FIELD(apta_waveform_span_t, columns);
    PRINT_TYPE(apta_waveform_overview_view_t);
    PRINT_FIELD(apta_waveform_overview_view_t, struct_size);
    PRINT_FIELD(apta_waveform_overview_view_t, api_version);
    PRINT_FIELD(apta_waveform_overview_view_t, level);
    PRINT_FIELD(apta_waveform_overview_view_t, state);
    PRINT_FIELD(apta_waveform_overview_view_t, confidence);
    PRINT_FIELD(apta_waveform_overview_view_t, reserved8);
    PRINT_FIELD(apta_waveform_overview_view_t, span_count);
    PRINT_FIELD(apta_waveform_overview_view_t, spans);
    PRINT_FIELD(apta_waveform_overview_view_t, flags);
    PRINT_FIELD(apta_waveform_overview_view_t, reserved32);
    PRINT_TYPE(apta_waveform_tile_view_t);
    PRINT_FIELD(apta_waveform_tile_view_t, struct_size);
    PRINT_FIELD(apta_waveform_tile_view_t, api_version);
    PRINT_FIELD(apta_waveform_tile_view_t, level_id);
    PRINT_FIELD(apta_waveform_tile_view_t, tile_index);
    PRINT_FIELD(apta_waveform_tile_view_t, source_range);
    PRINT_FIELD(apta_waveform_tile_view_t, first_column_index);
    PRINT_FIELD(apta_waveform_tile_view_t, column_count);
    PRINT_FIELD(apta_waveform_tile_view_t, columns);
    PRINT_FIELD(apta_waveform_tile_view_t, state);
    PRINT_FIELD(apta_waveform_tile_view_t, confidence);
    PRINT_FIELD(apta_waveform_tile_view_t, reserved8);
    PRINT_FIELD(apta_waveform_tile_view_t, flags);
    PRINT_FIELD(apta_waveform_tile_view_t, reserved32);
    PRINT_TYPE(apta_tempo_value_t);
    PRINT_FIELD(apta_tempo_value_t, struct_size);
    PRINT_FIELD(apta_tempo_value_t, api_version);
    PRINT_FIELD(apta_tempo_value_t, evidence_range);
    PRINT_FIELD(apta_tempo_value_t, applicability_range);
    PRINT_FIELD(apta_tempo_value_t, tempo_millibpm);
    PRINT_FIELD(apta_tempo_value_t, confidence);
    PRINT_FIELD(apta_tempo_value_t, reserved8);
    PRINT_FIELD(apta_tempo_value_t, reserved16);
    PRINT_FIELD(apta_tempo_value_t, state);
    PRINT_FIELD(apta_tempo_value_t, flags);
    PRINT_FIELD(apta_tempo_value_t, candidate_set_id);
    PRINT_FIELD(apta_tempo_value_t, reserved32);
    PRINT_TYPE(apta_tempo_candidate_t);
    PRINT_FIELD(apta_tempo_candidate_t, tempo_millibpm);
    PRINT_FIELD(apta_tempo_candidate_t, score);
    PRINT_FIELD(apta_tempo_candidate_t, confidence);
    PRINT_FIELD(apta_tempo_candidate_t, reserved8);
    PRINT_FIELD(apta_tempo_candidate_t, relation_to_selected);
    PRINT_FIELD(apta_tempo_candidate_t, flags);
    PRINT_TYPE(apta_tempo_view_t);
    PRINT_FIELD(apta_tempo_view_t, struct_size);
    PRINT_FIELD(apta_tempo_view_t, api_version);
    PRINT_FIELD(apta_tempo_view_t, selected);
    PRINT_FIELD(apta_tempo_view_t, candidate_count);
    PRINT_FIELD(apta_tempo_view_t, candidates);
    PRINT_FIELD(apta_tempo_view_t, flags);
    PRINT_FIELD(apta_tempo_view_t, reserved32);
    PRINT_TYPE(apta_grid_segment_t);
    PRINT_FIELD(apta_grid_segment_t, struct_size);
    PRINT_FIELD(apta_grid_segment_t, api_version);
    PRINT_FIELD(apta_grid_segment_t, applicability_range);
    PRINT_FIELD(apta_grid_segment_t, anchor_position);
    PRINT_FIELD(apta_grid_segment_t, anchor_ordinal);
    PRINT_FIELD(apta_grid_segment_t, frames_per_beat);
    PRINT_FIELD(apta_grid_segment_t, beat_count);
    PRINT_FIELD(apta_grid_segment_t, nominal_tempo_millibpm);
    PRINT_FIELD(apta_grid_segment_t, confidence);
    PRINT_FIELD(apta_grid_segment_t, reserved8);
    PRINT_FIELD(apta_grid_segment_t, reserved16);
    PRINT_FIELD(apta_grid_segment_t, state);
    PRINT_FIELD(apta_grid_segment_t, flags);
    PRINT_FIELD(apta_grid_segment_t, segment_id);
    PRINT_FIELD(apta_grid_segment_t, revision);
    PRINT_TYPE(apta_beat_t);
    PRINT_FIELD(apta_beat_t, position);
    PRINT_FIELD(apta_beat_t, ordinal);
    PRINT_FIELD(apta_beat_t, confidence);
    PRINT_FIELD(apta_beat_t, reserved8);
    PRINT_FIELD(apta_beat_t, reserved16);
    PRINT_FIELD(apta_beat_t, flags);
    PRINT_FIELD(apta_beat_t, revision);
    PRINT_TYPE(apta_grid_view_t);
    PRINT_FIELD(apta_grid_view_t, struct_size);
    PRINT_FIELD(apta_grid_view_t, api_version);
    PRINT_FIELD(apta_grid_view_t, requested_range);
    PRINT_FIELD(apta_grid_view_t, evidence_range);
    PRINT_FIELD(apta_grid_view_t, applicability_range);
    PRINT_FIELD(apta_grid_view_t, representation);
    PRINT_FIELD(apta_grid_view_t, state);
    PRINT_FIELD(apta_grid_view_t, confidence);
    PRINT_FIELD(apta_grid_view_t, reserved8);
    PRINT_FIELD(apta_grid_view_t, coverage_range_count);
    PRINT_FIELD(apta_grid_view_t, coverage_ranges);
    PRINT_FIELD(apta_grid_view_t, segment_count);
    PRINT_FIELD(apta_grid_view_t, segments);
    PRINT_FIELD(apta_grid_view_t, beat_count);
    PRINT_FIELD(apta_grid_view_t, beats);
    PRINT_FIELD(apta_grid_view_t, flags);
    PRINT_FIELD(apta_grid_view_t, reserved32);
    PRINT_TYPE(apta_source_info_t);
    PRINT_FIELD(apta_source_info_t, struct_size);
    PRINT_FIELD(apta_source_info_t, api_version);
    PRINT_FIELD(apta_source_info_t, total_frames);
    PRINT_FIELD(apta_source_info_t, sample_rate);
    PRINT_FIELD(apta_source_info_t, channel_count);
    PRINT_FIELD(apta_source_info_t, reserved16);
    PRINT_FIELD(apta_source_info_t, channel_layout);
    PRINT_FIELD(apta_source_info_t, fingerprint_kind);
    PRINT_FIELD(apta_source_info_t, fingerprint);
    PRINT_FIELD(apta_source_info_t, flags);
    PRINT_FIELD(apta_source_info_t, reserved32);
    PRINT_TYPE(apta_result_info_t);
    PRINT_FIELD(apta_result_info_t, struct_size);
    PRINT_FIELD(apta_result_info_t, api_version);
    PRINT_FIELD(apta_result_info_t, specification_major);
    PRINT_FIELD(apta_result_info_t, specification_minor);
    PRINT_FIELD(apta_result_info_t, producer_api_version);
    PRINT_FIELD(apta_result_info_t, container_version);
    PRINT_FIELD(apta_result_info_t, generation);
    PRINT_FIELD(apta_result_info_t, available_features);
    PRINT_FIELD(apta_result_info_t, changed_features);
    PRINT_FIELD(apta_result_info_t, session_state);
    PRINT_FIELD(apta_result_info_t, diagnostic_count);
    PRINT_FIELD(apta_result_info_t, flags);
    PRINT_FIELD(apta_result_info_t, lineage_id_high);
    PRINT_FIELD(apta_result_info_t, lineage_id_low);
    PRINT_TYPE(apta_diagnostic_view_t);
    PRINT_FIELD(apta_diagnostic_view_t, struct_size);
    PRINT_FIELD(apta_diagnostic_view_t, api_version);
    PRINT_FIELD(apta_diagnostic_view_t, code);
    PRINT_FIELD(apta_diagnostic_view_t, severity);
    PRINT_FIELD(apta_diagnostic_view_t, affected_features);
    PRINT_FIELD(apta_diagnostic_view_t, affected_range);
    PRINT_FIELD(apta_diagnostic_view_t, request_id);
    PRINT_FIELD(apta_diagnostic_view_t, flags);
    PRINT_FIELD(apta_diagnostic_view_t, message);
    PRINT_TYPE(apta_grid_revision_view_t);
    PRINT_FIELD(apta_grid_revision_view_t, struct_size);
    PRINT_FIELD(apta_grid_revision_view_t, api_version);
    PRINT_FIELD(apta_grid_revision_view_t, revision_id);
    PRINT_FIELD(apta_grid_revision_view_t, previous_revision_id);
    PRINT_FIELD(apta_grid_revision_view_t, state);
    PRINT_FIELD(apta_grid_revision_view_t, confidence);
    PRINT_FIELD(apta_grid_revision_view_t, reserved8);
    PRINT_FIELD(apta_grid_revision_view_t, affected_range);
    PRINT_FIELD(apta_grid_revision_view_t, proposed_representation);
    PRINT_FIELD(apta_grid_revision_view_t, proposed_segment_count);
    PRINT_FIELD(apta_grid_revision_view_t, proposed_beat_count);
    PRINT_FIELD(apta_grid_revision_view_t, flags);
    PRINT_FIELD(apta_grid_revision_view_t, reserved32);
    PRINT_FIELD(apta_grid_revision_view_t, reserved64);
    PRINT_TYPE(apta_serialize_options_t);
    PRINT_FIELD(apta_serialize_options_t, struct_size);
    PRINT_FIELD(apta_serialize_options_t, api_version);
    PRINT_FIELD(apta_serialize_options_t, flags);
    PRINT_FIELD(apta_serialize_options_t, reserved32);
    PRINT_FIELD(apta_serialize_options_t, maximum_output_bytes);
    PRINT_FIELD(apta_serialize_options_t, reserved64);
    PRINT_TYPE(apta_parse_options_t);
    PRINT_FIELD(apta_parse_options_t, struct_size);
    PRINT_FIELD(apta_parse_options_t, api_version);
    PRINT_FIELD(apta_parse_options_t, flags);
    PRINT_FIELD(apta_parse_options_t, maximum_section_count);
    PRINT_FIELD(apta_parse_options_t, maximum_overview_spans);
    PRINT_FIELD(apta_parse_options_t, maximum_waveform_columns);
    PRINT_FIELD(apta_parse_options_t, maximum_file_bytes);
    PRINT_FIELD(apta_parse_options_t, maximum_allocation_bytes);
    PRINT_FIELD(apta_parse_options_t, reserved64);
    PRINT_TYPE(apta_pcm_block_t);
    PRINT_FIELD(apta_pcm_block_t, struct_size);
    PRINT_FIELD(apta_pcm_block_t, api_version);
    PRINT_FIELD(apta_pcm_block_t, data);
    PRINT_FIELD(apta_pcm_block_t, planes);
    PRINT_FIELD(apta_pcm_block_t, first_frame);
    PRINT_FIELD(apta_pcm_block_t, frame_count);
    PRINT_FIELD(apta_pcm_block_t, flags);
    PRINT_FIELD(apta_pcm_block_t, reserved32);
    PRINT_TYPE(apta_pcm_source_t);
    PRINT_FIELD(apta_pcm_source_t, struct_size);
    PRINT_FIELD(apta_pcm_source_t, api_version);
    PRINT_FIELD(apta_pcm_source_t, user_data);
    PRINT_FIELD(apta_pcm_source_t, read_frames);
    PRINT_FIELD(apta_pcm_source_t, release_frames);
    PRINT_FIELD(apta_pcm_source_t, get_total_frames);
    PRINT_TYPE(apta_focus_t);
    PRINT_FIELD(apta_focus_t, struct_size);
    PRINT_FIELD(apta_focus_t, api_version);
    PRINT_FIELD(apta_focus_t, playhead_frame);
    PRINT_FIELD(apta_focus_t, lookbehind_frames);
    PRINT_FIELD(apta_focus_t, lookahead_frames);
    PRINT_FIELD(apta_focus_t, feature_mask);
    PRINT_FIELD(apta_focus_t, priority);
    PRINT_FIELD(apta_focus_t, flags);
    PRINT_FIELD(apta_focus_t, reserved16);
    PRINT_FIELD(apta_focus_t, reserved32);
    PRINT_TYPE(apta_region_request_t);
    PRINT_FIELD(apta_region_request_t, struct_size);
    PRINT_FIELD(apta_region_request_t, api_version);
    PRINT_FIELD(apta_region_request_t, range);
    PRINT_FIELD(apta_region_request_t, feature_mask);
    PRINT_FIELD(apta_region_request_t, soft_deadline_monotonic_ns);
    PRINT_FIELD(apta_region_request_t, request_id);
    PRINT_FIELD(apta_region_request_t, priority);
    PRINT_FIELD(apta_region_request_t, flags);
    PRINT_FIELD(apta_region_request_t, reserved16);
    PRINT_FIELD(apta_region_request_t, reserved32);
    PRINT_TYPE(apta_pcm_request_t);
    PRINT_FIELD(apta_pcm_request_t, struct_size);
    PRINT_FIELD(apta_pcm_request_t, api_version);
    PRINT_FIELD(apta_pcm_request_t, range);
    PRINT_FIELD(apta_pcm_request_t, feature_mask);
    PRINT_FIELD(apta_pcm_request_t, priority);
    PRINT_FIELD(apta_pcm_request_t, flags);
    PRINT_FIELD(apta_pcm_request_t, reserved16);
    PRINT_FIELD(apta_pcm_request_t, request_token);
    PRINT_FIELD(apta_pcm_request_t, reserved32);
    PRINT_TYPE(apta_work_budget_t);
    PRINT_FIELD(apta_work_budget_t, struct_size);
    PRINT_FIELD(apta_work_budget_t, api_version);
    PRINT_FIELD(apta_work_budget_t, maximum_input_frames);
    PRINT_FIELD(apta_work_budget_t, maximum_steps);
    PRINT_FIELD(apta_work_budget_t, soft_time_budget_us);
    PRINT_FIELD(apta_work_budget_t, flags);
    PRINT_TYPE(apta_progress_t);
    PRINT_FIELD(apta_progress_t, struct_size);
    PRINT_FIELD(apta_progress_t, api_version);
    PRINT_FIELD(apta_progress_t, consumed_input_frames);
    PRINT_FIELD(apta_progress_t, completed_steps);
    PRINT_FIELD(apta_progress_t, active_request_id);
    PRINT_FIELD(apta_progress_t, flags);
    PRINT_FIELD(apta_progress_t, published_generation);
    PRINT_FIELD(apta_progress_t, changed_features);
    PRINT_TYPE(apta_request_progress_t);
    PRINT_FIELD(apta_request_progress_t, struct_size);
    PRINT_FIELD(apta_request_progress_t, api_version);
    PRINT_FIELD(apta_request_progress_t, request_id);
    PRINT_FIELD(apta_request_progress_t, state);
    PRINT_FIELD(apta_request_progress_t, requested_range);
    PRINT_FIELD(apta_request_progress_t, requested_features);
    PRINT_FIELD(apta_request_progress_t, satisfied_features);
    PRINT_FIELD(apta_request_progress_t, progress_permille);
    PRINT_FIELD(apta_request_progress_t, diagnostic_code);
    PRINT_FIELD(apta_request_progress_t, flags);
    PRINT_FIELD(apta_request_progress_t, reserved32);
    PRINT_TYPE(apta_frame_range_t);
    PRINT_FIELD(apta_frame_range_t, struct_size);
    PRINT_FIELD(apta_frame_range_t, api_version);
    PRINT_FIELD(apta_frame_range_t, first_frame);
    PRINT_FIELD(apta_frame_range_t, end_frame);
    PRINT_TYPE(apta_fractional_frame_t);
    PRINT_FIELD(apta_fractional_frame_t, whole_frame);
    PRINT_FIELD(apta_fractional_frame_t, fraction_q32);
    PRINT_FIELD(apta_fractional_frame_t, reserved);
    PRINT_TYPE(apta_frame_period_t);
    PRINT_FIELD(apta_frame_period_t, whole_frames);
    PRINT_FIELD(apta_frame_period_t, fraction_q32);
    PRINT_FIELD(apta_frame_period_t, reserved);
    return 0;
}
